### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by innoreq** [friends-of-contao/contao-twitterreader#11] opened 2019-01-06 21:23 UTC
After having installed the plugin, adding a module to the backend, the following error appears when adding an article based on that module:

Attempted to load class "BackendTemplate" from namespace "FOC\TwitterReaderBundle". Did you forget a "use" statement for another namespace?

**Comment by hschottm** [comment] 2019-01-28 11:59
Which Contao version did you use to install the extension?
This error message appears when you add a module to the backend?

I can't reproduce this with an installation running Contao 4.4.x

**Comment by kikmedia** [comment] 2019-03-28 08:14
I can reproduce this, with a slightly different error:
`Attempted to load class "BackendTemplate" from namespace "FOC\TwitterReaderBundle". Did you forget a "use" statement for "Netzmacht\Contao\Toolkit\View\Template\BackendTemplate"?`

It appears whenever one includes a module of type 'Twitter Reader' into an article.

Reading that @innoreq got an error involving "BackendTemplate", I'm afraid this could be some interferent behaviour with other extensions modifying how BE templates are handled. In my case, this should be the Contao Leaflet bundle (indicated by 'Toolkit').

@innoreq Which other extensions did you install?

System: Contao 4.4.45, PHP 7.1.27 on Cyon web hosting. Do you need more information on my system, i.e. installed extensions?

**Comment by hschottm** [comment] 2019-03-29 09:51
Hi Carolina,

can you give me a list of the extensions that you have installed? I think it must be some interference with other extensions as I don't have this issue at all and I am using it in 2 different installations.

**Comment by hschottm** [comment] 2019-03-29 10:15
Fixed in 10ecaa63eaa3bc825628ec9dd323310d49edf40a

I added an explicit use statement to make clear that it is the \Contao\BackendTemplate that is used in the Bundle. I guess that was the problem when other extensions have been installed that were using a different BackendTemplate implementation.

I updated the Bundle to Version 2.0.2 on Packagist

**Closed by hschottm** 2019-03-29 10:15 UTC
